name: FEUCurrency
main: com.freshearth.currency.Plugin
version: 0.0.1
api-version: 1.20
description: A simple currency plugin for the FEU minecraft server
commands:
  currency:
    description: Base command
  pay:
    usage: /<command> <amount> to <account> [from [account]]
    description: Used to tranfer money from you account to another
  balance:
    usage: /<command> [user/top]
    description: Returns your current balance
    aliases: bal

permissions:
  feucurrency.*:
    description: Give access to all commands
    default: op
    children:
      feucurrency.user: true
      feucurrency.pay: true
      feucurrency.admin: true
  feucurrency.user:
    description: Give access to base user commands
    default: not op
  feucurrency.pay:
    description: Give access to pay command
    default: not op
  feucurrency.admin:
    description: Give access to admin commands
    default: op